

monitor: radiant.c radiant.h honeywell.c honeywell.h pv.c pv.h main.c thingspeak.c thingspeak.h growroom.c growroom.h greenhouse.c greenhouse.h
	cc -o monitor radiant.c honeywell.c pv.c thingspeak.c main.c growroom.c greenhouse.c -pthread
